name: Stock Volume Scan

on:
  workflow_dispatch:  # Allows the workflow to be triggered manually
  schedule:
    - cron: '0 4 * * *'  # Runs at 4 AM UTC daily

jobs:
  stock_volume_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yfinance

    - name: Run stock_volume_scan
      run: python -c "from get_stock_volume import scan_stock_volumes; scan_stock_volumes()"

    - name: Display stock volumes for debugging
      run: cat stock_volumes.txt

    - name: Commit and push changes
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add stock_volumes.txt
        git commit -m "Update Stock Volumes" || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git HEAD:main
